### ISSUE TITLE
[Improvement]: Improve the Amoro website

### ISSUE THREAD

**Issue by zhoujinsong** [apache/incubator-amoro#2702]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The Amoro website has been migrated from https://amoro.netease.com/ to https://amoro.apache.org/.

However, the content of the website needs to be improved to meet the requirements of ASF (Apache Software Foundation)[1] and to better guide project users and developers.

[1] https://infra.apache.org/website-guidelines.html

### How should we improve?

Improve the content of the Amoro website.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #2703 
- [x] #2705 
- [x] #2706 
- [x] #2707 
- [x] #2708 
- [x] #2709 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
